# Dependencies
highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: Mouli
tagline: 'Stay away. Personal space.'
description: "I tried not making this, but then that didn't work out so well."
url: http://csanivar.github.io
baseurl: '/'
paginate: 5
excerpt_separator: '<br>'
image: 'https://s.gravatar.com/avatar/4ff7017ab07ee94812cd8eefb8adf7ca?s=280'

gems:
- jekyll-paginate

author:
  name: 'Chandra Mouli'
  bio: 'Just a guy with internet connection'
  url: https://twitter.com/m_o_u_l_i
  email: mouli[dot]4543@gmail[dot]com
  github: csanivar
  twitter: m_o_u_l_i
  gravatar_md5: 4ff7017ab07ee94812cd8eefb8adf7ca

github:
  repo: https://github.com/csanivar

pages_list:
  Home: '/'
  About: '/about'
  Archive: '/archive'
  Tags: '/tags'
  RSS: 'atom.xml'
