# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Mouli
tagline:          'Stay away. Personal space.'
description:      'Fine. I admit: I am mouli'
url:              http://themouli.github.io
baseurl:		  /

author:
  name:           'Chandramouleshwar Sanivarapu'
  url:            https://twitter.com/themouli
  email:		  mouli.4543@gmail.com
  github:		  themouli
  twitter:		  themouli
  gravatar_md5:	  4ff7017ab07ee94812cd8eefb8adf7ca

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/themouli

pages_list:
  About: 		  '/about'
  Archive: 		  '/archive'
  Feed:			  '/atom.xml'
