# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Mouli
tagline:          'Stay away. Personal space.'
description:      'Fine. I admit: I am mouli'
url:              http://themouli.github.io

author:
  name:           'Chandramouleshwar Sanivarapu'
  url:            https://twitter.com/themouli
  email:		  mouli.4543@gmail.com

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/themouli
